# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: "Github-Asana bridge"

on:
  issues:
    types:
      - labeled

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    name: "Trigger after specific GH label was added"
    if: github.event.label.name == 'Asana'
    steps:
      - name: Check out bridger repository
        uses: actions/checkout@v3
        with:
          repository: mozmeao/asana-github-bridge
          ref: v1
          path: ./.github/actions/bridger
      - id: run-bridger
        name: Build bridge to Asana
        uses: ./.github/actions/bridger/issue_handler
        with:
            only-react-to: repo-org
            ASANA_PAT: ${{ secrets.ASANA_PAT }}
            ASANA_PROJECT: ${{ secrets.ASANA_PROJECT }}
            REPO_TOKEN: ${{ secrets.ASANA_GITHUB_BRIDGE_TOKEN }}
